apply:
  fields:
    platform:
      required: false
      default: dahua
      example: dahua
      selector:
        text:
    keep_names:
      required: false
      selector:
        object:
    reload_integrations:
      required: false
      default: true
      selector:
        boolean:
    notify:
      required: false
      default: true
      selector:
        boolean:
